import { notFound } from "next/navigation";
import { db } from "@/server/db";
import { journals } from "@/server/db/schema";
import { eq } from "drizzle-orm";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

interface Props {
  params: Promise<{
    slug: string;
  }>;
}

export default async function JournalEntryPage({ params }: Props) {
  const { slug } = await params;

  const [journal] = await db
    .select()
    .from(journals)
    .where(eq(journals.slug, slug))
    .limit(1);

  if (!journal) {
    notFound();
  }

  const formatDate = (date: Date | null) => {
    if (!date) return "";
    return new Date(date).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
  };

  return (
    <div className="min-h-screen pt-32 pb-24 px-8 bg-[#0A0A0A]">
      <div className="max-w-3xl mx-auto">
        <Link 
          href="/journal"
          className="inline-flex items-center gap-2 text-ash hover:text-gold-warm transition-colors font-sans text-xs tracking-[0.14em] uppercase mb-12"
        >
          <ArrowLeft size={14} />
          Back to Journal
        </Link>
        
        <p className="text-gold-warm text-xs tracking-[0.2em] uppercase font-sans mb-4">
          {journal.category}
        </p>
        
        <h1 className="font-display text-ivory font-light text-4xl md:text-5xl leading-tight mb-6">
          {journal.title}
        </h1>
        
        <div className="flex items-center gap-4 text-ash text-xs tracking-[0.1em] uppercase font-sans mb-12">
          <span>{formatDate(journal.createdAt)}</span>
          <span className="w-1 h-1 rounded-full bg-iron"></span>
          <span>{journal.readTime}</span>
        </div>

        {journal.imageUrl && (
          <div className="w-full aspect-[21/9] mb-16 relative overflow-hidden border border-iron/20">
            <div 
              className="absolute inset-0 bg-cover bg-center"
              style={{ backgroundImage: `url(${journal.imageUrl})` }}
            />
          </div>
        )}

        {/* Content area: Assuming HTML/Markdown-like safe content since it's generated by AI/Admin */}
        <div className="prose prose-invert prose-stone max-w-none prose-headings:font-display prose-headings:font-light prose-p:font-sans prose-p:font-light prose-p:leading-relaxed prose-a:text-gold-warm prose-a:no-underline hover:prose-a:text-gold-bright">
          <div dangerouslySetInnerHTML={{ __html: journal.content }} />
        </div>
        
        <div className="mt-20 pt-10 border-t border-iron/20 text-center">
          <p className="font-accent text-ivory text-xl tracking-[0.2em] uppercase mb-4">
            FRAVIONT
          </p>
          <p className="text-ash font-sans text-xs tracking-widest uppercase">
            The Art of Presence
          </p>
        </div>
      </div>
    </div>
  );
}
